# Generated by Django 4.1.2 on 2022-10-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый город', max_length=50)),
                ('description', models.CharField(blank=True, max_length=1500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
