# Generated by Django 4.1.2 on 2022-11-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_lomauser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='custom_background')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_%(model_name)s', to='users.lomauser')),
            ],
        ),
    ]
