# Generated by Django 4.1.2 on 2022-11-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombackground',
            name='background',
            field=models.ImageField(upload_to='static'),
        ),
    ]
