# Generated by Django 4.1.2 on 2022-10-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый', max_length=50)),
                ('update_settings', models.BooleanField(default=False)),
                ('change_stage', models.BooleanField(default=False)),
                ('update_orders', models.BooleanField(default=False)),
                ('update_product_info', models.BooleanField(default=False)),
                ('can_change_product_total_among', models.BooleanField(default=False)),
            ],
        ),
    ]
