# Generated by Django 4.1.2 on 2022-10-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, default='', max_length=50)),
                ('telegram_chat_id', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=False)),
                ('name', models.CharField(default='New Courier', max_length=50)),
                ('telegram_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('available_regions', models.ManyToManyField(blank=True, default={}, to='companies.region', verbose_name='Regions')),
            ],
        ),
    ]
