# Generated by Django 4.1.2 on 2022-10-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company'),
        ('couriers', '0002_alter_courier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
