# Generated by Django 4.1.2 on 2022-12-01 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orders_product',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='product_list',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 12, 17, 487015)),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 12, 17, 487015)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 12, 17, 487015)),
        ),
    ]
