# Generated by Django 4.1.2 on 2022-12-01 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orders_product_order_product_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_FIO',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 13, 30, 902656)),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 13, 30, 902656)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 13, 30, 902656)),
        ),
    ]
